name: Caller

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  matrix-gen:
    name: generate matrix
    runs-on: ubuntu-latest
    outputs:
      output-matrix: ${{ steps.generate.outputs.output-matrix }}
    steps:
      - id: generate
        run: |
          echo -n "::set-output name=output-matrix::{\"include\": [{\"key\": \"value1\"}, {\"key\": \"value2\"}]}"
          
  call-A:
    needs: [ matrix-gen ]
    uses: ./.github/workflows/called-A.yml
    with:
      matrix-input: ${{ needs.matrix-gen.outputs.output-matrix }}
